### ISSUE TITLE
Show loading bar for ember-data actions

### ISSUE THREAD

**Issue by adambedford** [tigressbailey/ember-cli-page-progress#4]
Is it possible to get the loading indicator to show for asynchronous Ember Data actions, such as saving a model?

I suppose one way would be to hook into `fetch` somehow so the loading bar is shown for all network requests. (Ember 3.15)

**Comment by tigressbailey** [comment]
@adambedford Thanks for the feedback. 
We'll have the Spring Festival in China from Jan 24th to Jan 30th.
I'll look into this ASAP.

**Comment by tigressbailey** [comment]
@adambedford Hello. I'm back.

This addon is built for indicating the route loading state, in which case, it is similar to YouTube.
It should be triggered when the route is actually changed.

If you are looking for async data action indicator, I recommend you use another loading spinner addon instead.
